version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_14.x | -E bash -
      - apt install -y nodejs
  
  pre_build:
    commands:
      - npm install
  
  build:
    commands:
      - npm start